__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & -1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Умножим 1 строку на -2 и сложим со 2 строкой. Умножим 1 строку на -1 и сложим с 3 строкой:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Разделим каждую строку матрицы на соответсвующий ведущий элемент: 1 строку на 1, 2 строку на -1, 3 строку на -2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
0 & 1 & -1 & -5 \\ 
0 & 0 & 1 & -\frac{3}{2}
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-2
\end{matrix}
\end{pmatrix}.$$

 Выразим  $x_1, x_2, x_3$  относительно остальных переменных:

<center>
$x_1=−x_2+x_3+2x_4$

$x_2=2+x_3+5x_4$

$x_3=−2+\frac{3}{2}x_4$
</center>
<h5>Решение:
<center>
$x_1=−2−3x_4$ 

$x_2=\frac{13}{2}x_4$

$x_3=−2+\frac{3}{2}x_4$

$x_4 - произвольное\quad действительное\quad число$
</center>
<h5>Частное решение:
<center>
$x_1=−2$

$x_2=0$

$x_3=−2$

$x_4=0$
</center>

In [1]:
import numpy as np

In [ ]:
def LU(A): 
  
    n = len(A)
    
    L = [[0 for _ in range(n)] for _ in range(n)]
    U = [[0 for _ in range(n)] for _ in range(n)] 
                  
    for i in range(n):
        for k in range(i, n):
            s = 0; 
            
            for j in range(i): 
                s += (L[i][j] * U[j][k]) 
  
            U[i][k] = A[i][k] - s
  
        for k in range(i, n): 
            if (i == k):
                L[i][i] = 1 
            else:
                s = 0
                
                for j in range(i): 
                    s += (L[k][j] * U[j][i])
  
                L[k][i] = ((A[k][i] - s) / U[i][i]) 
  
    return L, U

In [ ]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
#A = np.array([[1, 2, 3], [7, 11, 5], [8, 9, 4]])
b = np.array([0, -2, 4])
L, U = LU(A)



print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'L:\n{np.array(L)}\n')
print(f'U:\n{np.array(U)}\n')
print(f'LU:\n{np.array(L) @ np.array(U)}\n')
y = np.linalg.inv(np.array(L)) @ b
print(f'y:\n{y}\n')

x = np.linalg.inv(np.array(U)) @ y
print(f'x:\n{x}\n')

A:
[[ 1  1 -1 -2]
 [ 2  1 -1  1]
 [ 1  1 -3  1]]

b:
[ 0 -2  4]

L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 1. -0.  1.]]

U:
[[ 1.  1. -1.]
 [ 0. -1.  1.]
 [ 0.  0. -2.]]

LU:
[[ 1.  1. -1.]
 [ 2.  1. -1.]
 [ 1.  1. -3.]]

y:
[ 0. -2.  4.]

x:
[-2.  0. -2.]



__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Теорема__ 

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система имеет единственное решение.


In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 1

rank(A_ext): 2

# of vars: 3

Система несовместна.


In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система имеет бесконечное кол-во решений.


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система имеет единственное решение.


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Запишем систему в виде расширенной матрицы.<br>

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

1 строку умножим на 2 и вычтем и 2 строки.<br>
1 строку умножим на 3 и вычтем и 3 строки.<br>

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}.$$

2 строку умножим на 2 и вычтем из 3 строки. <br>

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a - 2b
\end{matrix}
\end{pmatrix}.$$

Если $c + a - 2b \neq 0$, то система несовместна.<br>