1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4 × 2 ,  𝐵  — матрица  4 × 2 ;

б)  𝐴  — матрица  2 × 5 ,  𝐵  — матрица  5 × 3 ;

в)  𝐴  — матрица  8 × 3 ,  𝐵  — матрица  3 × 8 ;

г)  𝐴  — квадратная матрица  4 × 4 ,  𝐵  — квадратная матрица  4 × 4 .

а) Нельзя перемножать, т.к. кол-во столбцов у матрицы А не совпадает с кол-вом строк у матрицы В. 

б) AB - 2 X 3 

в) AB - 8 X 8, BA - 3 X 3 

г) АВ - 4 X 4, BA - 4 X 4

2. Найти сумму и произведение матриц


$A = \begin{pmatrix}
1 & -2 \\
3 & 0
\end{pmatrix}$  и   $B = \begin{pmatrix}
4 & -1 \\
0 & 5
\end{pmatrix}$.

Решение:

$ 𝐴 + 𝐵 = \begin{pmatrix}
1 & −2\\
3 & 0
\end{pmatrix}
+ \begin{pmatrix}
4 &−1\\
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 -1\\
3 + 0 & 0 + 5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}
$


$ 𝐴 \cdot 𝐵 = \begin{pmatrix}
1 & −2\\
3 & 0
\end{pmatrix}
\cdot \begin{pmatrix}
4 &−1\\
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + -2 \cdot 0 & 1 \cdot (-1)-2 \cdot 5\\
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}
$


$ B \cdot A = \begin{pmatrix}
4 & −1\\
0 & 5
\end{pmatrix}
\cdot \begin{pmatrix}
1 & −2\\
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + -1 \cdot 3 & 4 \cdot (-2) + -1 \cdot 0\\
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = 
\begin{pmatrix}
1 & -8\\
15 & 0
\end{pmatrix}
$

In [1]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BА\n{B @ A}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BА
[[ 1 -8]
 [15  0]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3𝐴 − 2𝐵 + 4𝐶   для матриц  $𝐴 = \begin{pmatrix}
1 & 7 \\
3 & −6
\end{pmatrix} ,  𝐵 = \begin{pmatrix}
0 & 5 \\
2 & −1
\end{pmatrix} ,  𝐶 = \begin{pmatrix}
2 & −4 \\
1 & 1
\end{pmatrix}
$.

3A - 2B + 4C = $\begin{pmatrix}
3 & 21 \\
9 & 18
\end{pmatrix}
+ \begin{pmatrix}
0 & -10 \\
-4 & 2
\end{pmatrix}
+ \begin{pmatrix}
8 & -16 \\
4 & 4
\end{pmatrix}
= \begin{pmatrix}
3 + 0 + 8 & 21 - 10 - 16 \\
9 -4 + 4 & -18 +2 + 4
\end{pmatrix}
= \begin {pmatrix}
11 & -5 \\
9 & -12
\end{pmatrix}
$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3 * A - 2 * B + 4 * C}')

Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


4. Дана матрица  $ 𝐴 = \begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}.\quad Вычислить\   𝐴\cdot𝐴^T\ и\  𝐴^𝑇\cdot𝐴.
$

Транспонированная матрица: $ 𝐴^T = \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 
\end{pmatrix}.
$

$ 𝐴\cdot𝐴^T
=  \begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
·\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 
\end{pmatrix}
=  \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\
5 \cdot 4 - 2 \cdot 1 & 5 \cdot 5 - 2 \cdot (-2) & 5 \cdot 2 - 2 \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix}
= \begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}
$

$ 𝐴^T\cdot𝐴
=  \begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3 
\end{pmatrix}
·\begin{pmatrix}
4 & 1 \\
5 & -2 \\
2 & 3
\end{pmatrix}
=  \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\
1 \cdot 4 - 2 \cdot 5 + 3 \cdot 2 & 1 \cdot 1 - 2 \cdot (-2) + 3 \cdot 3 
\end{pmatrix}
= \begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}
$

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица 𝐴*𝐴𝑇\n{np.dot(A, A.T)}') # матрица корреляции
print(f'Матрица 𝐴𝑇*𝐴\n{np.dot(A.T, A)}') # матрица ковариации

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица 𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица 𝐴𝑇*𝐴
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [4]:
def skalar_prod(v1, v2):
    return sum([i * j for i, j in zip(v1, v2)])
       
def matrix_product(A, B, display_result=True):
    result = []
    try:
        for row_a in A:
            internal_row = []
            for k in range(len(B[0])):
                column = [B[i][k] for i in range(len(B))]
                internal_row.append(skalar_prod(row_a, column))
            result.append(internal_row)
        if display_result:
            for row in result:
                print(row)
        return result
    except Exception as e:
        print('wrong dimensions!')
        print(e)

In [5]:
# Проверка
a = [[1,2,3],
     [5,3,7]]
b = [[1,1],
     [2,2],
     [3,3]]
с = matrix_product(a,b)

[14, 14]
[32, 32]


In [6]:
# Сравнение с NUMPY
import numpy as np
a_np = np.array(a)
b_np = np.array(b)
a_np.dot(b_np)

array([[14, 14],
       [32, 32]])

## Часть вторая.

1. Вычислить определитель:

a)

\begin{vmatrix} 𝑠𝑖𝑛𝑥 & -𝑐𝑜𝑠𝑥 \\
𝑐𝑜𝑠𝑥 & 𝑠𝑖𝑛𝑥
\end{vmatrix}
 
б)

\begin{vmatrix} 
4 & 2 & 3 \\
0 & 5 & 1 \\
0 & 0 & 9
\end{vmatrix}
 
 в)

\begin{vmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}

a)
Определитель второго порядка, соответствующий этой матрице равен разности произведения элементов, стоящих на главной диагонали этой матрицы, и элементов, стоящих на ее побочной диагонали.

𝑠𝑖𝑛(𝑥) ⋅ 𝑠𝑖𝑛(𝑥) − 𝑐𝑜𝑠(𝑥) ⋅ (−𝑐𝑜𝑠(𝑥)) = 𝑠𝑖𝑛²(𝑥) + 𝑐𝑜𝑠²(𝑥) = 1

б) Данная матрица приведена к верхней треугольной форме, поэтому опредилитель будет равен произведению элементов по диагонали.

4 ⋅ 5 ⋅ 9 = 180


в) Ищем опредилитель раскладывая по строкам.


$
\begin{vmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{vmatrix} 
$
= 7⋅(12 − 15) − 8 ⋅ (6 − 12) + 9 ⋅ ( 5 − 8 ) = − 21 + 48 − 27 = 0


= 1⋅(45 − 48) − 2 ⋅ (36 − 42) + 3 ⋅ ( 32 − 35 ) = − 3 + 12 − 9 = 0


= −4⋅(18 − 24) + 5 ⋅ (9 − 21) − 6 ⋅ ( 6 − 12 ) = 24 − 60 + 36 = 0

2. Определитель матрицы  𝐴  равен  4 . Найти:

а)  𝑑𝑒𝑡($𝐴²$) ;

б)   𝑑𝑒𝑡($𝐴^𝑇$) ;

в)  𝑑𝑒𝑡($2𝐴$) .


а)  $𝑑𝑒𝑡(𝐴^2) = detA \cdot detA = 4 \cdot 4 = 16$

$б) detA^T = detA = 4$

$в)det(2A) = 2^ndetA = 4 \cdot 2^n $

3. Доказать, что матрица

\begin{pmatrix}
-2 & 7 & -3 \\
4 & -14 & 6 \\
-3 & 7 & 13
\end{pmatrix}
 
вырожденная.

*Решение:*

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

$Строка\ 1 \ и\ 2\ являются\ линейно\ зависимы:\quad \\
𝑥_2= −2⋅𝑥_1$
 


4. Найти ранг матрицы:

а)

\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 \\
2 & 3 & 4
\end{pmatrix}

\\

\begin{pmatrix}
1 & 2 & 3 \\
0 & -1 & -2 \\
0 & -1 & -2
\end{pmatrix}
 
б)

\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 4 & 3 \\
2 & 3 & 5 & 6
\end{pmatrix}

\\

\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 \\
2 & 3 & 5 & 6
\end{pmatrix}


а)

 Найдем ранг матрицы $A =
\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 \\
2 & 3 & 4
\end{pmatrix}$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 
\end{pmatrix}

rang = min(m, n)

m = 2, n = 3

rang A = 2




б)

Найдем ранг матрицы $A =
\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 4 & 3 \\
2 & 3 & 5 & 6
\end{pmatrix}$

Приведём матрицу А к треугольной форме - из каждой стоки вычитаем 2.
\begin{pmatrix}
0 & 0 & 0 & -1 \\
0 & 0 & 0 & 0 \\
0 & 0 & 2 & 1 \\
0 & 1 & 3 & 4
\end{pmatrix}

Транспонируем матрицу А, чтобы явно увидеть главную диагональ, т.к. (m = n), A = $A^T$
\begin{pmatrix}
-1 & 0 & 1 & 4 \\
0 & 0 & 2 & 3 \\
0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0
\end{pmatrix}

Удалим второй нулевой столбец и у нас получилась верхетреугольная матрица с (m = 3, n = 3), 
\begin{pmatrix}
-1 & 1 & 4 \\
0  & 2 & 3 \\
0  & 0 & 1 \\
0  & 0 & 0
\end{pmatrix}

соответственно rang A = 3. 


In [7]:
import numpy as np

x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [8]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
c = [2, 3, 5, 6]

a = np.array([x, y, z, c])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
