In [1]:
import numpy as np
import scipy.linalg

#### __1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [2]:
# а)

A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[ 1 -2]
 [ 7 -4]]

det(A1): 9.999999999999998

A2:
[[1 1]
 [3 7]]

det(A2): 3.999999999999999

x1 = 4.999999999999998
x2 = 1.9999999999999991


In [3]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = np.linalg.det(A3)

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86.00000000000004

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43.000000000000014

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 42.99999999999998

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


#### __2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а) Матрица коэффициентов:

### $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

Умножим 1 строку на 2 и вычтем из 2 строки:

Матрица U:<br>

### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
I_{31} & I_{32} & 1
\end{pmatrix}$$

Умножим 1 строку на 3 и вычтем из 3 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & I_{32} & 1
\end{pmatrix}$$

Умножим 2 строку на 4 и вычтем из 3 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [4]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]



б) Матрица коэффициентов:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$$

Умножим 1 строку на 2 и вычтем из 2 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
I_{31} & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$$

Умножим 1 строку на 3 и вычтем из 3 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
4 & 22 & 53 & 33
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$$

Умножим 1 строку на 4 и вычтем из 4 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$$

Умножим 2 строку на 5 и вычтем из 3 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 18 & 45 & 17
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$$

Умножим 2 строку на 6 и вычтем из 4 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & I_{43} & 1
\end{pmatrix}$$

Умножим 3 строку на 7 и вычтем из 4 строки:

Матрица U:

### $$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}$$

Матрица L:

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$$

In [5]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]



#### __3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [6]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

print(f'lu:\n{lu}\n')
print(f'piv:\n{piv}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.  0.  1.]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

lu:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

piv:
[1 2 2]



### $$\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{matrix}
\right|\begin{matrix}
1\\ 
-6\\
-5
\end{matrix}
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
\left.\begin{matrix}
2 & 1 & 3\\ 
22 & 14 & 10\\ 
18 & 16 & 8
\end{matrix}\right|
\begin{matrix}
1\\ 
-12\\
-10
\end{matrix}
\end{pmatrix}$$

### $$\begin{pmatrix}
2 & 1 & 3 \\ 
22 & 14 & 10 \\ 
18 & 16 & 8
\end{pmatrix} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 7 & -19
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3 & -23 \\ 
0 & 0 & \frac{104}{3}
\end{pmatrix}=U$$
### $$\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & l_{32} & 1
\end{pmatrix}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{pmatrix}
1 & 0 & 0 \\ 
11 & 1 & 0 \\ 
9 & \frac{7}{3} & 1
\end{pmatrix}=L$$

Решим систему $Ly=b$:

### $$\begin{cases}
y_1=1 \\
11y_{1}+y_2=-12 \\
9y_{1}+\frac{7}{3}y_{2}+y_{3}=-10
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
y_1=1 \\
y_2=-23 \\
y_{3}=\frac{104}{3}
\end{cases}$$

Решим систему $Ux=y$:
### $$\begin{cases}
2x_1+x_2+3x_3=1 \\
3x_2-23x_3=-23 \\
\frac{104}{3}x_3=\frac{104}{3}
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
x_1=-1 \\
x_2=0 \\
x_3=1
\end{cases}$$
Ответ: $(-1,0,1)$

#### __4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [7]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'K:\n{K}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

K:
(array([[  9.,  -5.,   5.],
       [-45.,   5.,   2.],
       [ 45., -15.,   3.]]), False)

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]



### $$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
### $$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
### $$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$
### $$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$$
### $$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}(-15+25)=\frac{10}{5}=2,$$
### $$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3.$$
Получили матрицу 
$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \;
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$
### $$\begin{cases}
9y_1=531, \\
-5y_1+5y_2=-460, \\
5y_1+2y_2+3y_3=193.
\end{cases} 
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
y_1=59, \\
y_2=-33, \\
y_3=-12.
\end{cases}$$
### $$\begin{cases}
9x_1-5x_2+5x_3=59, \\
5x_2+2x_3=-33, \\
3x_{3}=-12.
\end{cases}
\,\,\,\,\,\Rightarrow \,\,\,\,\,
\begin{cases}
x_1=6, \\
x_2=-5, \\
x_3=-4.
\end{cases}$$
Ответ: $(6,-5,-4)$

#### __5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [8]:
def LU(A): 
  
    n = len(A)
    
    L = [[0 for _ in range(n)] for _ in range(n)]
    U = [[0 for _ in range(n)] for _ in range(n)] 
                  
    for i in range(n):
        for k in range(i, n):
            s = 0; 
            
            for j in range(i): 
                s += (L[i][j] * U[j][k]) 
  
            U[i][k] = A[i][k] - s
  
        for k in range(i, n): 
            if (i == k):
                L[i][i] = 1 
            else:
                s = 0
                
                for j in range(i): 
                    s += (L[k][j] * U[j][i])
  
                L[k][i] = ((A[k][i] - s) / U[i][i]) 
  
    return L, U

In [9]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
#A = np.array([[1, 2, 3], [7, 11, 5], [8, 9, 4]])
b = np.array([1, -6, -5])
L, U = LU(A)



print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'L:\n{np.array(L)}\n')
print(f'U:\n{np.array(U)}\n')
print(f'LU:\n{np.array(L) @ np.array(U)}\n')
y = np.linalg.inv(np.array(L)) @ b
print(f'y:\n{y}\n')

x = np.linalg.inv(np.array(U)) @ y
print(f'x:\n{x}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

L:
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]

U:
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]

LU:
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]

y:
[  1.         -11.5         17.33333333]

x:
[-1.00000000e+00 -1.94716038e-15  1.00000000e+00]

